services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./glance/config:/app/config
      - ./glance/assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hdd:/mnt/hdd:ro
      - /mnt/hdd2:/mnt/hdd2:ro
      - /mnt/storage:/mnt/storage:ro
    ports:
      - 8088:8080
    env_file: ./glance/.env
  fourget:
    image: luuul/4get:latest
    container_name: fourget
    restart: unless-stopped
    environment:
      - FOURGET_PROTO=http
      - FOURGET_SERVER_NAME=Angus's server
    ports:
      - 8089:80
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve
    volumes:
      - ./kiwix:/data
    ports:
      - 8102:8080
    command: "*.zim"
networks: {}
