services:
  navidrome:
    image: deluan/navidrome:latest
#    user: 1000:1000
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "./navidrome:/data"
      - "/mnt/storage/Music:/music:ro"
