services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      OAUTH_PROVIDER_NAME: authentik
      OPENID_PROVIDER_URL: https://auth.home.paillaugue.fr/application/o/open-webui/.well-known/openid-configuration
      OPENID_REDIRECT_URI: https://open-webui.home.paillaugue.fr/oauth/oidc/callback
      WEBUI_URL: https://open-webui.home.paillaugue.fr
      # Allows auto-creation of new users using OAuth. Must be paired with ENABLE_LOGIN_FORM=false.
      ENABLE_OAUTH_SIGNUP: true
      # Disables user/password login form. Required when ENABLE_OAUTH_SIGNUP=true.
      ENABLE_LOGIN_FORM: false
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
    ports:
      - "8095:8080"
    volumes:
      - ./open-webui/open-webui:/app/backend/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_ORIGINS="*"
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped

  edge-tts:
    image: travisvn/openai-edge-tts:latest
    container_name: edge-tts
    ports:
      - "5050:5050"
