# For ressource optimization, see lazymc

services:
  vanilla:
    image: itzg/minecraft-server
    container_name: vanilla
    tty: true
    stdin_open: true
    restart: no
    environment:
      EULA: TRUE
      MEMORY: 2G
      VERSION: 1.21.6
      MOTD: "My survival server"
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_PROJECTS: |
        fabric-api
        toms-storage:YTzOMaus
        chunk-loaders:Tu5ARCZQ
      TYPE: FABRIC
    volumes:
      - ./vanilla:/data
    ports:
      - "25565:25565"
